# Generated by Django 5.1.1 on 2024-09-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
