# Generated by Django 5.1.1 on 2024-09-30 09:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_avatar.jpg', max_length=255, verbose_name='image'),
        ),
    ]
